[pytest]
filterwarnings =
    ignore:.*oneOf.*:pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:.*parseString.*:pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:.*resetCache.*:pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:.*enablePackrat.*:pyparsing.exceptions.PyparsingDeprecationWarning
